### ISSUE TITLE
'System.IO.FileNotFoundException' in BencodeNET.dll

### ISSUE THREAD

**Issue by mashoko** [SuRGeoNix/TorSwarm#1]
+		Exception	Exception thrown: 'System.IO.FileNotFoundException' in BencodeNET.dll ("Could not load file or assembly 'System.Buffers, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.")	System.IO.FileNotFoundException

**Comment by SuRGeoNix** [comment]
It seems there is something wrong with your libraries, make sure you have installed the required packages :-

![image](https://user-images.githubusercontent.com/57474895/90376143-ac556480-e07e-11ea-886d-d24bc982d5a1.png)
